### ISSUE TITLE
coco correct_bedgraph usage

### ISSUE THREAD

**Issue by vetmohit89** [scottgroup/coco#2]
Hello,

Thanks for making this tool. I could able to run first two parts but having difficulty in running the third part. In manual file, you have mentioned basic usage as follow:
coco correct_bedgraph <args> path/to/your/bam/alignment.bam path/to/your/output.bedgraph

It did not work as it require genomepath file. 

Then I tried with gtf file as genome file "human_ensembl_87_wo_dup_v2.BB_v3.correct_annotation.correct_annotation.gtf" but it failed with the errror Input error: Chromosome chr10 found in your input file but not in your genome file.
genomecov exit status: 256. Please help!!!

**Comment by Gabrielle-DF** [comment]
Hi,

Thanks for your interest in CoCo!

The genome file is a file required by BedTools. It must contain two columns separated by a tab, the first column is the name of the chromosome written the same way as in you bam file and the second is the length of the chromosome.

If you used STAR for the alignment, you can use the file `chrNameLength.txt` present in the STAR index folder. Otherwise, you can find the information in your bam header using the command `samtools view -H myfile.bam | grep '@SQ'` and keeping only the chromosomes name and length without the prefixes SN: and LN:.

I will adjust the manual to reflect this, thank you for reporting it.
